Homework7
nekirilova/niffler-st4 pull request #6
Opened 2024-02-03 12:33 UTC by nekirilova

2024-02-05 06:09 UTC, sashkir7 requested changes
Необходимы правки. 
Разберитесь, пожалуйста, почему в extension-классе нельзя хранить мутабельные (изменяемые) данные на уровне класса

2024-02-05 06:09 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +            connection.setAutoCommit(false);
Когда мы выполняем единичный sql-запрос на модификацию, то connection.setAutoCommit(false); можно не указывать.

2024-02-05 06:09 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/UserAuthExtension.java
> +    private UserEntity user;
На уровне extension-класса мутабельные (изменяемые) данные хранить нельзя
Дело в том, что Junit создает единственный экземпляр данного класса для всех тестов. То есть во время параллельного запуска тестов могут быть проблемы, которые отследить и воспроизвести довольно тяжело. Это важно!

2024-02-05 06:09 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/UserAuthExtension.java
> +                password = new Faker().internet().password();
Можно экземпляр Faker вынести на уровень класса

2024-02-05 06:09 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/UserAuthExtension.java
> +                    .put("userAuth", userAuth);
Пара моментов:
1. В store нужно класть данные под уникальным для теста id. Опять же, чтобы во время параллельного прогона тестов у нас не было конфликтов (у каждого теста будет свой id - своя "ячейка" в хранилище).
2. Добавлять нужно обе сущности: userAuth и user. Для этого, например, можно создать новый класс, который хранит обе сущности. Либо же использовать иную структуру, например, мапу

2024-02-05 06:09 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/UserAuthExtension.java
> +        userRepository.deleteInUserDataById(user.getId());
Еще раз: нельзя использовать свойства класса для хранения изменяемых данных.
Для этих целей существует store. И в данном методе мы должны данные получать именно оттуда

2024-02-08 16:13 UTC, nekirilova commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +            connection.setAutoCommit(false);
Убрала)

2024-02-08 17:33 UTC, nekirilova commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/UserAuthExtension.java
> +                password = new Faker().internet().password();
Вынесла

2024-02-08 17:58 UTC, nekirilova commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/UserAuthExtension.java
> +    private UserEntity user;
Поняла, исправила)

2024-02-08 17:59 UTC, nekirilova commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/UserAuthExtension.java
> +                    .put("userAuth", userAuth);
поправила с мапой

2024-02-08 17:59 UTC, nekirilova commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/UserAuthExtension.java
> +        userRepository.deleteInUserDataById(user.getId());
Исправила

2024-02-09 04:53 UTC, sashkir7 approved these changes

2024-02-09 15:23 UTC, merged